---
- name: Restart services
  become: true
  ansible.builtin.systemd:
    name: "{{ app_name }}-{{ item.name }}.service"
    daemon_reload: true
    state: restarted
  loop:
    "{{ app_services }}"

- name: Enable timers
  become: true
  ansible.builtin.systemd:
    name: "{{ app_name }}-{{ item.name }}.timer"
    daemon_reload: true
    state: restarted
  loop:
    "{{ app_timers }}"
