---
- name: List services
  become: true
  register: app_services_existing
  ansible.builtin.find:
    paths:
      - "/etc/systemd/system"
    pattern:
      - "{{ app_name }}-*"

- name: Pause and disable services
  become: true
  ansible.builtin.systemd:
    name: "{{ item.path | basename }}"
    enabled: false
    state: stopped
  loop:
    "{{ app_services_existing.files }}"
