---
- name: Create the app directory
  become: true
  ansible.builtin.file:
    path: "{{ app_root }}"
    state: directory
    mode: "0775"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Create the data directory
  become: true
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Create the app directory
  become: true
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: "0775"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Create the config directory
  become: true
  ansible.builtin.file:
    path: "{{ app_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Register one level of files in data_dir
  become: true
  ansible.builtin.find:
    paths: "{{ app_data_dir }}"
    patterns: "*"
  register: app_data_files
